Add DAHDI group
nethesis/comps pull request #48
Opened 2020-11-02 15:52 UTC by gsanchietti

DAHDI is no more a dependency for freepbx package

NethServer/dev#6319

**Note**: remember to push translations to transifex after merge

2020-11-02 16:20 UTC, DavidePrincipi requested changes

2020-11-02 16:20 UTC, DavidePrincipi commented on nethserver-enterprise-groups.xml.in
> +      <_name>DAHDI divers and tools</_name>
```suggestion
      <_name>DAHDI drivers and tools</_name>
```

2020-11-02 16:25 UTC, gsanchietti commented on nethserver-enterprise-groups.xml.in
> +      <_name>DAHDI divers and tools</_name>
I've fixed it while you're were writing the review :)

2020-11-02 16:27 UTC, DavidePrincipi approved these changes

2020-11-03 10:49 UTC, Stell0 approved these changes

2020-11-23 13:07 UTC, merged